language: python

python:
  - 2.7 # this is a cheat here because travis doesn't do 2.4-2.6

install:
- pip install -e .
- pip install -r requirements-dev.txt

script:
- python ./setup.py develop && COMPILE='--compile' make check

# blacklist
branches:
  except:
    - data-driven-pytest
